// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::ray_cast_hit_type::RayCastHit;
use super::ray_cast_type::RayCast;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_raycasts`.
///
/// Obtain a handle from the [`PhysicsRaycastsTableAccess::physics_raycasts`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_raycasts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_raycasts().on_insert(...)`.
pub struct PhysicsRaycastsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RayCast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_raycasts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsRaycastsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsRaycastsTableHandle`], which mediates access to the table `physics_raycasts`.
    fn physics_raycasts(&self) -> PhysicsRaycastsTableHandle<'_>;
}

impl PhysicsRaycastsTableAccess for super::RemoteTables {
    fn physics_raycasts(&self) -> PhysicsRaycastsTableHandle<'_> {
        PhysicsRaycastsTableHandle {
            imp: self.imp.get_table::<RayCast>("physics_raycasts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsRaycastsInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsRaycastsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsRaycastsTableHandle<'ctx> {
    type Row = RayCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RayCast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsRaycastsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRaycastsInsertCallbackId {
        PhysicsRaycastsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsRaycastsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsRaycastsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRaycastsDeleteCallbackId {
        PhysicsRaycastsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsRaycastsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RayCast>("physics_raycasts");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsRaycastsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsRaycastsTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsRaycastsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsRaycastsUpdateCallbackId {
        PhysicsRaycastsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsRaycastsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RayCast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RayCast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_raycasts`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsRaycastsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_raycasts().id().find(...)`.
pub struct PhysicsRaycastsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RayCast, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsRaycastsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_raycasts`.
    pub fn id(&self) -> PhysicsRaycastsIdUnique<'ctx> {
        PhysicsRaycastsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsRaycastsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RayCast> {
        self.imp.find(col_val)
    }
}
