// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::quat_type::Quat;
use super::rigid_body_type::RigidBody;
use super::rigid_body_type_type::RigidBodyType;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_rigid_bodies`.
///
/// Obtain a handle from the [`PhysicsRigidBodiesTableAccess::physics_rigid_bodies`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_rigid_bodies()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_rigid_bodies().on_insert(...)`.
pub struct PhysicsRigidBodiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RigidBody>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_rigid_bodies`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsRigidBodiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsRigidBodiesTableHandle`], which mediates access to the table `physics_rigid_bodies`.
    fn physics_rigid_bodies(&self) -> PhysicsRigidBodiesTableHandle<'_>;
}

impl PhysicsRigidBodiesTableAccess for super::RemoteTables {
    fn physics_rigid_bodies(&self) -> PhysicsRigidBodiesTableHandle<'_> {
        PhysicsRigidBodiesTableHandle {
            imp: self.imp.get_table::<RigidBody>("physics_rigid_bodies"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsRigidBodiesInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsRigidBodiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsRigidBodiesTableHandle<'ctx> {
    type Row = RigidBody;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RigidBody> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsRigidBodiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodiesInsertCallbackId {
        PhysicsRigidBodiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsRigidBodiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsRigidBodiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodiesDeleteCallbackId {
        PhysicsRigidBodiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsRigidBodiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RigidBody>("physics_rigid_bodies");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsRigidBodiesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsRigidBodiesTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsRigidBodiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodiesUpdateCallbackId {
        PhysicsRigidBodiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsRigidBodiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RigidBody>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RigidBody>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_rigid_bodies`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsRigidBodiesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_rigid_bodies().id().find(...)`.
pub struct PhysicsRigidBodiesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RigidBody, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsRigidBodiesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_rigid_bodies`.
    pub fn id(&self) -> PhysicsRigidBodiesIdUnique<'ctx> {
        PhysicsRigidBodiesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsRigidBodiesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RigidBody> {
        self.imp.find(col_val)
    }
}
