// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::rigid_body_properties_type::RigidBodyProperties;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_rigid_body_properties`.
///
/// Obtain a handle from the [`PhysicsRigidBodyPropertiesTableAccess::physics_rigid_body_properties`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_rigid_body_properties()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_rigid_body_properties().on_insert(...)`.
pub struct PhysicsRigidBodyPropertiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RigidBodyProperties>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_rigid_body_properties`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsRigidBodyPropertiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsRigidBodyPropertiesTableHandle`], which mediates access to the table `physics_rigid_body_properties`.
    fn physics_rigid_body_properties(&self) -> PhysicsRigidBodyPropertiesTableHandle<'_>;
}

impl PhysicsRigidBodyPropertiesTableAccess for super::RemoteTables {
    fn physics_rigid_body_properties(&self) -> PhysicsRigidBodyPropertiesTableHandle<'_> {
        PhysicsRigidBodyPropertiesTableHandle {
            imp: self
                .imp
                .get_table::<RigidBodyProperties>("physics_rigid_body_properties"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsRigidBodyPropertiesInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsRigidBodyPropertiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsRigidBodyPropertiesTableHandle<'ctx> {
    type Row = RigidBodyProperties;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RigidBodyProperties> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsRigidBodyPropertiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodyPropertiesInsertCallbackId {
        PhysicsRigidBodyPropertiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsRigidBodyPropertiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsRigidBodyPropertiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodyPropertiesDeleteCallbackId {
        PhysicsRigidBodyPropertiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsRigidBodyPropertiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<RigidBodyProperties>("physics_rigid_body_properties");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsRigidBodyPropertiesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsRigidBodyPropertiesTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsRigidBodyPropertiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsRigidBodyPropertiesUpdateCallbackId {
        PhysicsRigidBodyPropertiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsRigidBodyPropertiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RigidBodyProperties>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RigidBodyProperties>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_rigid_body_properties`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsRigidBodyPropertiesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_rigid_body_properties().id().find(...)`.
pub struct PhysicsRigidBodyPropertiesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RigidBodyProperties, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsRigidBodyPropertiesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_rigid_body_properties`.
    pub fn id(&self) -> PhysicsRigidBodyPropertiesIdUnique<'ctx> {
        PhysicsRigidBodyPropertiesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsRigidBodyPropertiesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RigidBodyProperties> {
        self.imp.find(col_val)
    }
}
