// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::collider_type::Collider;
use super::collider_type_type::ColliderType;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_colliders`.
///
/// Obtain a handle from the [`PhysicsCollidersTableAccess::physics_colliders`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_colliders()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_colliders().on_insert(...)`.
pub struct PhysicsCollidersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Collider>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_colliders`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsCollidersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsCollidersTableHandle`], which mediates access to the table `physics_colliders`.
    fn physics_colliders(&self) -> PhysicsCollidersTableHandle<'_>;
}

impl PhysicsCollidersTableAccess for super::RemoteTables {
    fn physics_colliders(&self) -> PhysicsCollidersTableHandle<'_> {
        PhysicsCollidersTableHandle {
            imp: self.imp.get_table::<Collider>("physics_colliders"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsCollidersInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsCollidersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsCollidersTableHandle<'ctx> {
    type Row = Collider;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Collider> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsCollidersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsCollidersInsertCallbackId {
        PhysicsCollidersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsCollidersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsCollidersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsCollidersDeleteCallbackId {
        PhysicsCollidersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsCollidersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Collider>("physics_colliders");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsCollidersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsCollidersTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsCollidersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsCollidersUpdateCallbackId {
        PhysicsCollidersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsCollidersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Collider>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Collider>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_colliders`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsCollidersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_colliders().id().find(...)`.
pub struct PhysicsCollidersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Collider, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsCollidersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_colliders`.
    pub fn id(&self) -> PhysicsCollidersIdUnique<'ctx> {
        PhysicsCollidersIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsCollidersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Collider> {
        self.imp.find(col_val)
    }
}
