// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::physics_world_tick_type::PhysicsWorldTick;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PhysicsTickWorldArgs {
    pub tick: PhysicsWorldTick,
}

impl From<PhysicsTickWorldArgs> for super::Reducer {
    fn from(args: PhysicsTickWorldArgs) -> Self {
        Self::PhysicsTickWorld { tick: args.tick }
    }
}

impl __sdk::InModule for PhysicsTickWorldArgs {
    type Module = super::RemoteModule;
}

pub struct PhysicsTickWorldCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `physics_tick_world`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait physics_tick_world {
    /// Request that the remote module invoke the reducer `physics_tick_world` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_physics_tick_world`] callbacks.
    fn physics_tick_world(&self, tick: PhysicsWorldTick) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `physics_tick_world`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PhysicsTickWorldCallbackId`] can be passed to [`Self::remove_on_physics_tick_world`]
    /// to cancel the callback.
    fn on_physics_tick_world(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PhysicsWorldTick) + Send + 'static,
    ) -> PhysicsTickWorldCallbackId;
    /// Cancel a callback previously registered by [`Self::on_physics_tick_world`],
    /// causing it not to run in the future.
    fn remove_on_physics_tick_world(&self, callback: PhysicsTickWorldCallbackId);
}

impl physics_tick_world for super::RemoteReducers {
    fn physics_tick_world(&self, tick: PhysicsWorldTick) -> __sdk::Result<()> {
        self.imp
            .call_reducer("physics_tick_world", PhysicsTickWorldArgs { tick })
    }
    fn on_physics_tick_world(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PhysicsWorldTick) + Send + 'static,
    ) -> PhysicsTickWorldCallbackId {
        PhysicsTickWorldCallbackId(self.imp.on_reducer(
            "physics_tick_world",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PhysicsTickWorld { tick },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, tick)
            }),
        ))
    }
    fn remove_on_physics_tick_world(&self, callback: PhysicsTickWorldCallbackId) {
        self.imp.remove_on_reducer("physics_tick_world", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `physics_tick_world`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_physics_tick_world {
    /// Set the call-reducer flags for the reducer `physics_tick_world` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn physics_tick_world(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_physics_tick_world for super::SetReducerFlags {
    fn physics_tick_world(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("physics_tick_world", flags);
    }
}
