// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::quat_type::Quat;
use super::trigger_type::Trigger;
use super::vec_3_type::Vec3;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `physics_triggers`.
///
/// Obtain a handle from the [`PhysicsTriggersTableAccess::physics_triggers`] method on [`super::RemoteTables`],
/// like `ctx.db.physics_triggers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_triggers().on_insert(...)`.
pub struct PhysicsTriggersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Trigger>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `physics_triggers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PhysicsTriggersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PhysicsTriggersTableHandle`], which mediates access to the table `physics_triggers`.
    fn physics_triggers(&self) -> PhysicsTriggersTableHandle<'_>;
}

impl PhysicsTriggersTableAccess for super::RemoteTables {
    fn physics_triggers(&self) -> PhysicsTriggersTableHandle<'_> {
        PhysicsTriggersTableHandle {
            imp: self.imp.get_table::<Trigger>("physics_triggers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PhysicsTriggersInsertCallbackId(__sdk::CallbackId);
pub struct PhysicsTriggersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PhysicsTriggersTableHandle<'ctx> {
    type Row = Trigger;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Trigger> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PhysicsTriggersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTriggersInsertCallbackId {
        PhysicsTriggersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PhysicsTriggersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PhysicsTriggersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PhysicsTriggersDeleteCallbackId {
        PhysicsTriggersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PhysicsTriggersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Trigger>("physics_triggers");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct PhysicsTriggersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PhysicsTriggersTableHandle<'ctx> {
    type UpdateCallbackId = PhysicsTriggersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PhysicsTriggersUpdateCallbackId {
        PhysicsTriggersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PhysicsTriggersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Trigger>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Trigger>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `physics_triggers`,
/// which allows point queries on the field of the same name
/// via the [`PhysicsTriggersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.physics_triggers().id().find(...)`.
pub struct PhysicsTriggersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Trigger, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PhysicsTriggersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `physics_triggers`.
    pub fn id(&self) -> PhysicsTriggersIdUnique<'ctx> {
        PhysicsTriggersIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PhysicsTriggersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Trigger> {
        self.imp.find(col_val)
    }
}
