// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RigidBodyProperties {
    pub id: u64,
    pub world_id: u64,
    pub friction_static_coefficient: f32,
    pub friction_dynamic_coefficient: f32,
    pub restitution_coefficient: f32,
    pub mass: f32,
    pub inv_mass: f32,
}

impl __sdk::InModule for RigidBodyProperties {
    type Module = super::RemoteModule;
}
