// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShootPlayerArgs {}

impl From<ShootPlayerArgs> for super::Reducer {
    fn from(args: ShootPlayerArgs) -> Self {
        Self::ShootPlayer
    }
}

impl __sdk::InModule for ShootPlayerArgs {
    type Module = super::RemoteModule;
}

pub struct ShootPlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `shoot_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait shoot_player {
    /// Request that the remote module invoke the reducer `shoot_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_shoot_player`] callbacks.
    fn shoot_player(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `shoot_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ShootPlayerCallbackId`] can be passed to [`Self::remove_on_shoot_player`]
    /// to cancel the callback.
    fn on_shoot_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ShootPlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_shoot_player`],
    /// causing it not to run in the future.
    fn remove_on_shoot_player(&self, callback: ShootPlayerCallbackId);
}

impl shoot_player for super::RemoteReducers {
    fn shoot_player(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("shoot_player", ShootPlayerArgs {})
    }
    fn on_shoot_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ShootPlayerCallbackId {
        ShootPlayerCallbackId(self.imp.on_reducer(
            "shoot_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ShootPlayer {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_shoot_player(&self, callback: ShootPlayerCallbackId) {
        self.imp.remove_on_reducer("shoot_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `shoot_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_shoot_player {
    /// Set the call-reducer flags for the reducer `shoot_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn shoot_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_shoot_player for super::SetReducerFlags {
    fn shoot_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("shoot_player", flags);
    }
}
